from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Sequence

from ..mapping import BitSegment
from .ramulator2 import Ramulator2Adapter


@dataclass(frozen=True)
class Ramulator21HBM3Config:
    """Explicit Ramulator2.1 HBM3 component selection.

    Defaults mirror the upstream HBM3 smoke/throughput configurations rather
    than inventing a local DRAM timing model. Controller and address-mapping
    choices remain visible and are written into every run manifest.
    """

    org_preset: str = "HBM3_8Gb_8hi"
    timing_preset: str = "HBM3_6400Mbps"
    num_channels: int = 1
    frontend_clock_ratio: int = 4
    memory_clock_ratio: int = 1
    scheduler: str = "FRFCFSRowHit"
    row_policy: str = "Open"
    addr_mapper: str = "RoBaRaCoCh"
    refresh_manager: str = "HBM34PerBankRefresh"
    transaction_bytes: int = 32

    def __post_init__(self) -> None:
        if self.num_channels <= 0 or self.num_channels & (self.num_channels - 1):
            raise ValueError("num_channels must be a positive power of two")
        if self.frontend_clock_ratio <= 0 or self.memory_clock_ratio <= 0:
            raise ValueError("clock ratios must be > 0")
        if self.transaction_bytes <= 0:
            raise ValueError("transaction_bytes must be > 0")


@dataclass(frozen=True)
class Ramulator21Run:
    controller_cycles: int
    transaction_count: int
    trace_path: str
    trace_sha256: str
    runner_path: str
    runner_sha256: str
    config: Dict[str, object]
    stats: Dict[str, object]
    stdout: str

    def write_manifest(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(asdict(self), indent=2, sort_keys=True))
        return path


def _sha(path: Path) -> str:
    h = hashlib.sha256(path.read_bytes()).hexdigest()
    return h


class Ramulator21HBM3Adapter:
    """Official Ramulator2.1 Python-API backend for Pure-NPU HBM3 traces.

    The adapter writes the same ordered flat-address LoadStoreTrace used by the
    CModel, generates an explicit Python runner composed only from upstream
    Ramulator2.1 components, executes it in a subprocess, and captures the
    nested `sim.stats` as JSON. No DRAM timing equations are duplicated here.
    """

    STATS_PREFIX = "RRAM_CMODEL_RAMULATOR21_STATS="

    def __init__(
        self,
        cfg: Ramulator21HBM3Config | None = None,
        python_executable: str | Path = sys.executable,
    ) -> None:
        self.cfg = cfg or Ramulator21HBM3Config()
        self.python_executable = str(python_executable)
        # Reuse the exact transaction-address generator used by the legacy
        # binary/YAML backend without requiring a binary or template at run time.
        self._trace_helper = Ramulator2Adapter(
            executable=".",
            config_template=".",
            transaction_bytes=self.cfg.transaction_bytes,
        )

    def write_load_trace(self, segments: Sequence[BitSegment], path: str | Path) -> Path:
        return self._trace_helper.write_load_trace(segments, path)

    def render_runner(self, trace_path: str | Path, output_path: str | Path) -> Path:
        trace = str(Path(trace_path).resolve())
        cfg = self.cfg
        script = f'''# Auto-generated by rram_cmodel.backends.ramulator21\nimport json\nimport ramulator\n\ntrace_path = {trace!r}\nfrontend = ramulator.frontend.LoadStoreTrace(\n    clock_ratio={cfg.frontend_clock_ratio},\n    path=trace_path,\n)\n\ndram = ramulator.dram.HBM3(\n    org_preset={cfg.org_preset!r},\n    timing_preset={cfg.timing_preset!r},\n)\n\nscheduler = getattr(ramulator.scheduler, {cfg.scheduler!r})()\nrow_policy = getattr(ramulator.row_policy, {cfg.row_policy!r})()\naddr_mapper = getattr(ramulator.addr_mapper, {cfg.addr_mapper!r})()\nrefresh_manager = getattr(ramulator.refresh_manager, {cfg.refresh_manager!r})()\n\ndef make_controller():\n    return ramulator.controller.HBM34(\n        dram=dram,\n        scheduler=scheduler,\n        refresh_manager=refresh_manager,\n        row_policy=row_policy,\n        addr_mapper=addr_mapper,\n    )\n\ncontrollers = [make_controller() for _ in range({cfg.num_channels})]\nmem = ramulator.memory_system.GenericDRAM(\n    clock_ratio={cfg.memory_clock_ratio},\n    controllers=controllers,\n    channel_mapper=ramulator.channel_mapper.CacheLineInterleave(),\n)\n\nsim = ramulator.Simulation(frontend, mem)\nsim.run()\nstats = sim.stats\nprint({self.STATS_PREFIX!r} + json.dumps(stats, sort_keys=True))\n'''
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script)
        return output_path

    @staticmethod
    def _controller_cycles(stats: Dict[str, object]) -> int:
        memory = stats.get("memory_system")
        if not isinstance(memory, dict):
            raise RuntimeError("Ramulator2.1 stats missing memory_system")
        controller = memory.get("controller")
        if isinstance(controller, dict):
            if "cycles" not in controller:
                raise RuntimeError("Ramulator2.1 controller stats missing cycles")
            return int(controller["cycles"])
        if isinstance(controller, list) and controller:
            cycles = []
            for item in controller:
                if not isinstance(item, dict) or "cycles" not in item:
                    raise RuntimeError("Malformed multi-channel controller stats")
                cycles.append(int(item["cycles"]))
            return max(cycles)
        raise RuntimeError("Ramulator2.1 stats missing controller data")

    def run(self, trace_path: str | Path, runner_path: str | Path) -> Ramulator21Run:
        trace_path = Path(trace_path)
        runner_path = Path(runner_path)
        if not trace_path.exists():
            raise FileNotFoundError(trace_path)
        if not runner_path.exists():
            raise FileNotFoundError(runner_path)
        proc = subprocess.run(
            [self.python_executable, str(runner_path)],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        stats = None
        for line in proc.stdout.splitlines():
            if line.startswith(self.STATS_PREFIX):
                stats = json.loads(line[len(self.STATS_PREFIX):])
        if not isinstance(stats, dict):
            raise RuntimeError("Ramulator2.1 runner did not emit JSON stats")
        transactions = sum(1 for line in trace_path.read_text().splitlines() if line.strip())
        return Ramulator21Run(
            controller_cycles=self._controller_cycles(stats),
            transaction_count=transactions,
            trace_path=str(trace_path),
            trace_sha256=_sha(trace_path),
            runner_path=str(runner_path),
            runner_sha256=_sha(runner_path),
            config=asdict(self.cfg),
            stats=stats,
            stdout=proc.stdout,
        )

    def run_segments(
        self,
        segments: Sequence[BitSegment],
        workdir: str | Path,
        stem: str = "hbm3_weight_trace",
    ) -> Ramulator21Run:
        workdir = Path(workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        trace = self.write_load_trace(segments, workdir / f"{stem}.trace")
        runner = self.render_runner(trace, workdir / f"{stem}_ramulator21.py")
        result = self.run(trace, runner)
        result.write_manifest(workdir / f"{stem}.run.json")
        return result
